---
- name: Add organizations
  theforeman.foreman.organization:
    name:                               "{{ foreman_organizations_item.name }}"
    description:                        "{{ foreman_organizations_item.description | default(omit) }}"
    label:                              "{{ foreman_organizations_item.label | default(omit) }}"
    server_url:                         "{{ foreman_organizations_item.server_url | default(omit) }}"
    username:                           "{{ foreman_organizations_item.username | default(omit) }}"
    password:                           "{{ foreman_organizations_item.password | default(omit) }}"
    validate_certs:                     "{{ foreman_organizations_item.validate_certs | default(omit) }}"
    parameters:                         "{{ foreman_organizations_item.parameters | default(omit) }}"
    state:                              "{{ foreman_organizations_item.state | default(omit) }}"
  loop: "{{ foreman_organizations }}"
  loop_control:
    loop_var: foreman_organizations_item
  no_log: "{{ foreman_configuration_organizations_secure_logging }}"